basePath: /api/v1
definitions:
  internal_app_handler.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: http://localhost:8082
info:
  contact:
    email: bitop@spatecon.ru
    name: API Support
    url: https://vk.com/bmstu_schedule
  description: Bmstu Open IT Platform
  license:
    name: AS IS (NO WARRANTY)
  title: BITOP
  version: "1.0"
paths:
  /api/v1/elements:
    get:
      consumes:
      - application/json
      description: Get list of all elements with optional search by name
      parameters:
      - description: Search query by element name
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_app_handler.ErrorResponse'
      summary: Get all elements
      tags:
      - elements
schemes:
- https
- http
swagger: "2.0"
